image: "debian:latest"
stages:
  - build
patch_and_build_signal:
  stage: build
  script:
    - "apt update && apt install -y git"
    - "apt install -y default-jdk"
    - "apt install -y lib32stdc++6 unzip wget"
    - "wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip" # download android sdk
    - "echo '444e22ce8ca0f67353bda4b85175ed3731cae3ffa695ca18119cbacef1c1bea0  sdk-tools-linux-3859397.zip' |sha256sum -c"
    - "unzip sdk-tools-linux-3859397.zip -d /sdk-tools-linux" # unzip android sdk
    - "yes | /sdk-tools-linux/tools/bin/sdkmanager --licenses || true" # to accept licenses
    - "export JAVA_OPTS=\"-Xmx3096M\""
    - "export GRADLE_OPTS=\"-Dorg.gradle.jvmargs=-Xmx4608M\""
    - "export ANDROID_HOME=\"/sdk-tools-linux\"" # set ANDROID_HOME env var
    - "git clone https://github.com/WhisperSystems/Signal-Android.git && cd Signal-Android && git checkout v4.19.3" # get signal sources
    - "./gradlew clean" # cleanup
    - "git apply $CI_PROJECT_DIR/destroy-gcm-support.patch" # apply our patch
    - "./gradlew assembleWebsiteRelease" #assembleWebsiteDebug
    - "mkdir -p $CI_PROJECT_DIR/artifacts"
    - "find $CI_PROJECT_DIR/Signal-Android/build/outputs -name *.apk"
    - "mv $(find $CI_PROJECT_DIR/Signal-Android/build/outputs -name *.apk) $CI_PROJECT_DIR/artifacts"
    - "ls -lh $CI_PROJECT_DIR/artifacts"
    # To sign packages ; you'll need a keystore with your certificate
    # signing packages is important, it also allows application update without removing previous installed version of the app
    # To build the keystore used here, we use:
    #   keytool -genkey -v -keystore keystore.keystore -keyalg RSA -keysize 2048 -validity 10000 -alias app
    #   cat keystore.keystore | base64 > keystore.base64
    # then we provide that base64 encoded file to the CI ; you'll get it back to its original format write after this command is run:
    - "echo \"$KEYSTORE_CRT\" |base64 -d > /keystore.keystore"
    - "for f in $CI_PROJECT_DIR/artifacts/*unsigned*.apk; do SIGNED_FNAME=\"$(echo $f |sed 's/unsigned/signed/g')\"; echo \"Signing $f\"; jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore /keystore.keystore -storepass \"$KEYSTORE_PASSPHR\" $f -signedjar \"$SIGNED_FNAME\" app ;done"
    - "rm $CI_PROJECT_DIR/artifacts/*unsigned*.apk"
    - "ls -lh $CI_PROJECT_DIR/artifacts"
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/artifacts/*.apk"
  only:
    - master
    
    
    
    